apiVersion: v1
kind: Service
metadata:
  labels:
    app: rpc-bench-server
  name: rpc-bench-server
  namespace: default
spec:
  selector:
    app: rpc-bench-server
  type: ClusterIP
  ports:
  - name: grpc
    port: 18000
    targetPort: 18000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-bench-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpc-bench-server
  template:
    metadata:
      name: rpc-bench-server
      annotations:
        inject.istio.io/templates: grpc-agent
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
      labels:
        app: rpc-bench-server
    spec:
      containers:
      - name: rpc-bench-box
        image: rpc-bench-box
        imagePullPolicy: Never
        command: ["sleep"]
        args: ["1h"]
        ports:
        - containerPort: 18000
        volumeMounts:
        - name: nfs
          mountPath: /nfs
        securityContext:
          capabilities:
            add: ["SYS_PTRACE", "SYS_NICE", "SYS_ADMIN"]
      volumes:
      - name: nfs
        hostPath:
          path: /nfs
      nodeSelector:
        kubernetes.io/hostname: danyang-06
